
services:
  php:
    image: fsilva/php:8.2-cli
    volumes:
      - ./:/var/www/app
    environment:
      - USE_XDEBUG=yes
      - XDEBUG_MODE=develop,debug,coverage
      - ENABLE_OPCACHE=no
      - ENABLE_XDEBUG_FOR_MAC=no
